require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe EnquiriesController do

  def mock_enquiry(stubs={})
    @mock_enquiry ||= mock_model(Enquiry, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all enquiries as @enquiries" do
      Enquiry.stub(:all) { [mock_enquiry] }
      get :index
      assigns(:enquiries).should eq([mock_enquiry])
    end
  end

  describe "GET show" do
    it "assigns the requested enquiry as @enquiry" do
      Enquiry.stub(:find).with("37") { mock_enquiry }
      get :show, :id => "37"
      assigns(:enquiry).should be(mock_enquiry)
    end
  end

  describe "GET new" do
    it "assigns a new enquiry as @enquiry" do
      Enquiry.stub(:new) { mock_enquiry }
      get :new
      assigns(:enquiry).should be(mock_enquiry)
    end
  end

  describe "GET edit" do
    it "assigns the requested enquiry as @enquiry" do
      Enquiry.stub(:find).with("37") { mock_enquiry }
      get :edit, :id => "37"
      assigns(:enquiry).should be(mock_enquiry)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created enquiry as @enquiry" do
        Enquiry.stub(:new).with({'these' => 'params'}) { mock_enquiry(:save => true) }
        post :create, :enquiry => {'these' => 'params'}
        assigns(:enquiry).should be(mock_enquiry)
      end

      it "redirects to the created enquiry" do
        Enquiry.stub(:new) { mock_enquiry(:save => true) }
        post :create, :enquiry => {}
        response.should redirect_to(enquiry_url(mock_enquiry))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved enquiry as @enquiry" do
        Enquiry.stub(:new).with({'these' => 'params'}) { mock_enquiry(:save => false) }
        post :create, :enquiry => {'these' => 'params'}
        assigns(:enquiry).should be(mock_enquiry)
      end

      it "re-renders the 'new' template" do
        Enquiry.stub(:new) { mock_enquiry(:save => false) }
        post :create, :enquiry => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested enquiry" do
        Enquiry.stub(:find).with("37") { mock_enquiry }
        mock_enquiry.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :enquiry => {'these' => 'params'}
      end

      it "assigns the requested enquiry as @enquiry" do
        Enquiry.stub(:find) { mock_enquiry(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:enquiry).should be(mock_enquiry)
      end

      it "redirects to the enquiry" do
        Enquiry.stub(:find) { mock_enquiry(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(enquiry_url(mock_enquiry))
      end
    end

    describe "with invalid params" do
      it "assigns the enquiry as @enquiry" do
        Enquiry.stub(:find) { mock_enquiry(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:enquiry).should be(mock_enquiry)
      end

      it "re-renders the 'edit' template" do
        Enquiry.stub(:find) { mock_enquiry(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested enquiry" do
      Enquiry.stub(:find).with("37") { mock_enquiry }
      mock_enquiry.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the enquiries list" do
      Enquiry.stub(:find) { mock_enquiry }
      delete :destroy, :id => "1"
      response.should redirect_to(enquiries_url)
    end
  end

end
